
### list of notes
GET  http://localhost:3001/notes

### create a new note
POST  http://localhost:3001/notes
Content-Type: application/json

{
  "title":"read book"
}

### get a note
GET http://localhost:3001/notes/1

### update a note
PATCH  http://localhost:3001/notes/7
Content-Type: application/json

{
  "title":"read book1"
}

### delete a note
DELETE http://localhost:3001/notes/2